version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      nx-dependencies:
        patterns:
          - "@nx*"
      eslint-dependencies:
        patterns:
          - "eslint"
      types-dependencies:
        patterns:
          - "types"
      jest-dependencies:
        patterns:
          - "jest"
      other-dependencies:
        patterns:
          - "*"
