version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      dependencies:
        patterns:
          - '*'
    ignore:
      - dependency-name: 'esbuild'
        versions: ['>=0.19.13']
      - dependency-name: 'eslint-config-prettier'
        versions: ['>=9.0.1']
