changelog:
  categories:
    - title: 🏕 Features
      labels:
        - '*'
      exclude:
        labels:
          - 'Bug'
          - 'Dependencies'
    - title: 🐛 Bug
      labels:
        - 'Bug'
