changelog:
  categories:
    - title: 🏕 Features
      labels:
        - '*'
      exclude:
        labels:
          - :bug: Bug
          - dependencies
    - title: 🐛 Bug
      labels:
        - :bug: Bug
    - title: 👒 Dependencies
      labels:
        - dependencies
