name: Deploy [Configs]
run-name: Deploy to ${{ inputs.environment }} by @${{ github.actor }} on ${{ inputs.version || github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (v4.0.0.0)'
        type: string
env:
  FORCE_COLOR: 2
  NODE: 24

jobs:
  main:
    name: Build & Bundle & Publish
    environment:
      name: ${{inputs.environment}}
      url: ${{ steps.release.outputs.url}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      discussions: write
    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '${{ env.NODE }}'
          registry-url: https://npm.pkg.github.com
          scope: ${{github.repository_owner}}
          cache: 'npm'
      - uses: nrwl/nx-set-shas@826660b82addbef3abff5fa871492ebad618c9e1 # v4
      - run: npm ci
      - name: Build Configurations Page
        run: |
          npx nx run acf-configs:build --prod --base https://configs.getautoclicker.com/ --verbose --skip-nx-cache
        env:
          VITE_PUBLIC_VARIANT: ${{vars.VITE_PUBLIC_VARIANT}}
          VITE_PUBLIC_I18N: ${{vars.VITE_PUBLIC_I18N}}
          VITE_PUBLIC_FIREBASE_API_KEY: ${{vars.VITE_PUBLIC_FIREBASE_API_KEY}}
          VITE_PUBLIC_FIREBASE_DATABASE_URL: ${{vars.VITE_PUBLIC_FIREBASE_DATABASE_URL}}
          VITE_PUBLIC_FIREBASE_PROJECT_ID: ${{vars.VITE_PUBLIC_FIREBASE_PROJECT_ID}}
          VITE_PUBLIC_FIREBASE_AUTH_DOMAIN: https://configs.getautoclicker.com/
          VITE_PUBLIC_FIREBASE_BUCKET: ${{vars.VITE_PUBLIC_FIREBASE_BUCKET}}
          VITE_PUBLIC_RELEASE_VERSION: ${{inputs.version || github.ref_name}}
          VITE_PUBLIC_ALGOLIA_APP_ID: ${{vars.VITE_PUBLIC_ALGOLIA_APP_ID}}
          VITE_PUBLIC_ALGOLIA_SEARCH_API_KEY: ${{vars.VITE_PUBLIC_ALGOLIA_SEARCH_API_KEY}}
      - name: Print Environment Info
        run: npx nx report
      - name: Configs to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@e2eda2e106cfa35cdbcf4ac9ddaf6c4756df2c8c #v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: auto-clicker-autofill
          target: auto-clicker-autofill-configs
          channelId: live
