name: E2E [Build, Deploy & Test]
run-name: E2E Deploy to ${{ inputs.environment || 'Development' }} by @${{ github.actor }}

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment of release'
        type: environment
        default: Development
        required: true
      deploy_options_page:
        description: 'Build & deploy options page to Firebase'
        type: boolean
        default: false
        required: false
      grep:
        description: 'Filter tests by name (e.g. feat-a)'
        type: string
        default: 'test'
        required: false

env:
  FORCE_COLOR: 2
  NODE: 22

jobs:
  main:
    name: Build, Deploy & E2E
    environment:
      name: ${{ inputs.environment || 'Development' }}
      url: 'https://auto-clicker-auto-fill-playwright.web.app/'
    runs-on: ubuntu-latest
    env:
      VITE_PUBLIC_URL: ${{ vars.VITE_PUBLIC_URL }}
    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '${{ env.NODE }}'
          registry-url: https://npm.pkg.github.com
          scope: ${{ github.repository_owner }}

      - uses: nrwl/nx-set-shas@826660b82addbef3abff5fa871492ebad618c9e1 # v4
      - name: Install dependencies
        run: npm ci

      - name: Download Extension Artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: acf-extension-${{ vars.VITE_PUBLIC_VARIANT }}
          path: acf-extension-artifact

      - name: Extract Extension
        run: |
          mkdir -p apps/acf-extension/dist
          unzip -o acf-extension-artifact/acf-extension-${{ vars.VITE_PUBLIC_VARIANT }}.zip -d apps/acf-extension/dist

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - name: Run E2E Tests
        continue-on-error: true
        run: npx nx run acf-options-page:e2e --skip-nx-cache ${{ inputs.grep && format('-- --grep="{0}"', inputs.grep) || '-- --grep="test"' }}
