name: mono-repo

on:
  workflow_dispatch:
  pull_request:
    branches: main

env:
  UNINSTALL_URL: ${{vars.UNINSTALL_URL}}
  TRACKING_ID: ${{vars.TRACKING_ID}}
  OPTIONS_PAGE_URL: ${{vars.OPTIONS_PAGE_URL}}
  FUNCTION_URL: ${{vars.FUNCTION_URL}}
  VARIANT: ${{vars.VARIANT}}
  DISCORD_CLIENT_ID: ${{vars.DISCORD_CLIENT_ID}}
  NAME: ${{vars.NAME}}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Use variables
        run: |
          echo "repository variable : $REPOSITORY_VAR"
          echo "variable from shell environment : $UNINSTALL_URL"
        env:
          REPOSITORY_VAR: ${{ vars.DISCORD_CLIENT_ID }}
          OVERRIDE_VAR: ${{ vars.VARIANT }}

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.0
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    with:
      number-of-agents: 3
      environment-variables: |
        UNINSTALL_URL=${{vars.UNINSTALL_URL}}
        TRACKING_ID=${{vars.TRACKING_ID}}
        OPTIONS_PAGE_URL=${{vars.OPTIONS_PAGE_URL}}
        FUNCTION_URL=${{vars.FUNCTION_URL}}
        VARIANT=${{vars.VARIANT}}
        DISCORD_CLIENT_ID=${{vars.DISCORD_CLIENT_ID}}
        NAME=${{vars.NAME}}
        TEST=true
