name: mono-repo

on:
  workflow_dispatch:
  pull_request:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  EnvSetup:
    name: Setup Dynamic Environment Variables
    runs-on: ubuntu-latest
    environment: Development
    outputs:
      UNINSTALL_URL: ${{ steps.set-output-defaults.outputs.UNINSTALL_URL}}
      TRACKING_ID: ${{ steps.set-output-defaults.outputs.TRACKING_ID}}
      OPTIONS_PAGE_URL: ${{ steps.set-output-defaults.outputs.OPTIONS_PAGE_URL}}
      FUNCTION_URL: ${{ steps.set-output-defaults.outputs.FUNCTION_URL}}
      VARIANT: ${{ steps.set-output-defaults.outputs.VARIANT}}
      DISCORD_CLIENT_ID: ${{ steps.set-output-defaults.outputs.DISCORD_CLIENT_ID}}
      NAME: ${{ steps.set-output-defaults.outputs.NAME}}
    steps:
      - name: set outputs with default values
        id: set-output-defaults
        run: |
          echo "VARIANT=${{ vars.VARIANT }}" >> $GITHUB_OUTPUT
          echo "UNINSTALL_URL=${{ vars.UNINSTALL_URL }}" >> $GITHUB_OUTPUT
          echo "TRACKING_ID=${{ vars.TRACKING_ID }}" >> $GITHUB_OUTPUT
          echo "OPTIONS_PAGE_URL=${{ vars.OPTIONS_PAGE_URL }}" >> $GITHUB_OUTPUT
          echo "FUNCTION_URL=${{ vars.FUNCTION_URL }}" >> $GITHUB_OUTPUT
          echo "DISCORD_CLIENT_ID=${{ vars.DISCORD_CLIENT_ID }}" >> $GITHUB_OUTPUT
          echo "NAME=${{ vars.NAME }}" >> $GITHUB_OUTPUT

  main:
    needs: [EnvSetup]
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.0
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    with:
      parallel-commands: |
        npx nx-cloud record -- npx nx format:check
      artifacts-path: 'dist/apps/*'
      environment-variables: |
        VARIANT=${{needs.EnvSetup.outputs.VARIANT}}
        UNINSTALL_URL=${{needs.EnvSetup.outputs.UNINSTALL_URL}}
        TRACKING_ID=${{needs.EnvSetup.outputs.TRACKING_ID}}
        OPTIONS_PAGE_URL=${{needs.EnvSetup.outputs.OPTIONS_PAGE_URL}}
        FUNCTION_URL=${{needs.EnvSetup.outputs.FUNCTION_URL}}
        DISCORD_CLIENT_ID=${{needs.EnvSetup.outputs.DISCORD_CLIENT_ID}}
        NAME=${{needs.EnvSetup.outputs.NAME}}
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=test --parallel=3 --exclude='tag:puppeteer' --ci --code-coverage
        npx nx affected --target=build --parallel=3 --exclude='tag:puppeteer,tag:extension'
        npx nx run acf-extension:package

  agents:
    needs: [EnvSetup]
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.0
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    with:
      number-of-agents: 3
      environment-variables: |
        VARIANT=${{needs.EnvSetup.outputs.VARIANT}}
        UNINSTALL_URL=${{needs.EnvSetup.outputs.UNINSTALL_URL}}
        TRACKING_ID=${{needs.EnvSetup.outputs.TRACKING_ID}}
        OPTIONS_PAGE_URL=${{needs.EnvSetup.outputs.OPTIONS_PAGE_URL}}
        FUNCTION_URL=${{needs.EnvSetup.outputs.FUNCTION_URL}}
        DISCORD_CLIENT_ID=${{needs.EnvSetup.outputs.DISCORD_CLIENT_ID}}
        NAME=${{needs.EnvSetup.outputs.NAME}}

  extension:
    needs: [agents, main]
    runs-on: ubuntu-latest
    name: Extension
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: nx-main-artifacts
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .

  tag:
    needs: extension
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - name: Set ${{vars.VARIANT}} Tag
        uses: rickstaa/action-create-tag@v1
        with:
          force_push_tag: true
          tag: '${{vars.VARIANT}}'
